Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,8 +1,9 @@
 #!/bin/sh
-
-PACKAGE=$1
+REPO=$1
+PACKAGE=$2
 APK_FILE="${PACKAGE}.apk"
-APK_URL="https://dl-cdn.alpinelinux.org/alpine/latest-stable/main/x86_64/$APK_FILE"
+APK_URL_COMMUNITY="https://dl-cdn.alpinelinux.org/alpine/latest-stable/community/x86_64/$APK_FILE"
+APK_URL_MAIN="https://dl-cdn.alpinelinux.org/alpine/latest-stable/main/x86_64/$APK_FILE"
 TMP_DIR="/mnt/external/0/lavender.env/tmp"
 ROOTFS="/mnt/external/0"
 TRACK_DIR="/mnt/external/0/lavender.env/installed"
@@ -20,7 +21,11 @@ mkdir -p "$TMP_DIR" "$TRACK_DIR"
 cd "$TMP_DIR" || { log_error "Failed to go to $TMP_DIR"; exit 1; }
 
 log_info "Downloading: $APK_URL"
-curl -s -O "$APK_URL" || { log_error "Error loading $PACKAGE"; exit 1; }
+if [$REPO == "community"]; then
+  curl -s -O "$APK_URL_COMMUNITY" || { log_error "Error loading $PACKAGE"; exit 1; }
+elfi [$REPO == "main"]; then
+  curl -s -O "$APK_URL_MAIN" || { log_error "Error loading $PACKAGE"; exit 1; }
+fi
 
 log_info "Checking archive contents..."
 tar -tf "$APK_FILE" > /dev/null 2>&1 || {
